Geo\Domain\Model\Province:
  properties:
    name:
      - NotBlank:
          message: validation.error.field.must_not_be_blank
    isDeleted:
      - Type:
          type: boolean
          message: validation.error.field.wrong_type
